export function renderStateUi(nonce: string, authenticated: boolean, csrfToken?: string): string {
  const body = authenticated
    ? `<header><div><p class="eyebrow">Local runtime</p><h1>BrowserMCP Bridge</h1></div><span id="running" class="pill">Loading…</span></header>
      <main>
        <section><h2>Endpoints</h2><div id="endpoints" class="grid"></div></section>
        <section><div class="section-heading"><div><p class="eyebrow">Explicit consent</p><h2>Pending Origin approvals</h2></div><span id="approval-count" class="pill">0 pending</span></div><p class="muted">Approve only an exact Origin and app identity you recognize. An approval authenticates the waiting connection; no credential is returned to the web page.</p><div id="approvals" class="stack empty">No pending approvals.</div></section>
        <section><h2>Connected web apps</h2><div id="apps" class="stack empty">No connected apps.</div></section>
        <section><details><summary>Legacy one-time token pairing</summary><p class="muted">Compatibility path for integrations that cannot wait for operator approval. Prefer the request list above for browser apps.</p><form id="pair"><label>Exact web Origin<input name="origin" type="url" placeholder="https://example.com" required></label><button>Issue one-time token</button></form><output id="pair-output"></output></details></section>
        <section><h2>Published capabilities</h2><div id="capabilities" class="grid"></div></section>
        <section><h2>Recent requests</h2><div id="requests" class="stack empty">No requests yet.</div></section>
        <section><h2>Recent logs</h2><div id="logs" class="stack empty">No logs yet.</div></section>
      </main>`
    : `<main class="login"><section><p class="eyebrow">Local runtime</p><h1>BrowserMCP Bridge</h1><p>Enter the admin token printed once when the Bridge started. It is exchanged for an HttpOnly, SameSite session cookie and is not stored by this page.</p><form id="login"><label>Admin token<input name="token" type="password" autocomplete="off" required></label><button>Open status</button></form><output id="login-output"></output></section></main>`;

  const script = authenticated
    ? `const esc=(v)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const csrf=${JSON.stringify(csrfToken ?? "")};const renderList=(id,items,render,empty)=>{const el=document.getElementById(id);el.classList.toggle('empty',items.length===0);el.innerHTML=items.length?items.map(render).join(''):empty};
async function refresh(){const response=await fetch('/api/state',{cache:'no-store'});if(response.status===401){location.reload();return}const s=await response.json();
document.getElementById('running').textContent=s.running?'Running':'Stopped';
document.getElementById('endpoints').innerHTML='<article><b>MCP</b><code>'+esc(s.mcpEndpoint)+'</code></article><article><b>Browser</b><code>'+esc(s.browserEndpoint)+'</code></article>';
const approvals=s.pairingRequests??[];document.getElementById('approval-count').textContent=approvals.length+' pending';
renderList('approvals',approvals,a=>'<article class="approval"><div><b>'+esc(a.origin)+'</b><span>'+esc(a.app.name)+' · '+esc(a.app.id)+' · '+esc(a.app.version)+'</span><small>runtime '+esc(a.runtime.id)+' / instance '+esc(a.runtime.instanceId)+'</small><small>expires '+esc(new Date(a.expiresAt).toLocaleString())+'</small></div><div class="actions"><button data-approval="'+esc(a.requestId)+'" data-decision="approve">Approve</button><button class="danger" data-approval="'+esc(a.requestId)+'" data-decision="reject">Reject</button></div></article>','No pending approvals.');
renderList('apps',s.apps,a=>'<article><b>'+esc(a.name)+'</b><span>'+esc(a.id)+' · '+esc(a.version)+'</span><code>'+esc(a.origin)+'</code><small>runtime '+esc(a.runtimeId)+' / instance '+esc(a.instanceId)+'</small></article>','No connected apps.');
document.getElementById('capabilities').innerHTML=['tools','resources','prompts'].map(k=>'<article><b>'+k+'</b><strong>'+s.capabilities[k].length+'</strong><small>'+s.capabilities[k].map(esc).join(', ')+'</small></article>').join('');
renderList('requests',s.recentRequests,r=>'<article><b>'+esc(r.kind)+'</b><span class="'+esc(r.outcome)+'">'+esc(r.outcome)+'</span><small>'+esc(r.appId)+' · '+esc(r.durationMs??'pending')+' ms'+(r.result?' · '+esc(r.result.kind)+' result ('+esc(r.result.itemCount)+')':'')+(r.error?' · '+esc(r.error.code)+': '+esc(r.error.message):'')+'</small></article>','No requests yet.');
renderList('logs',s.logs,l=>'<article><b>'+esc(l.level)+'</b><span>'+esc(l.message)+'</span><small>'+esc(l.at)+'</small></article>','No logs yet.');}
document.getElementById('approvals').addEventListener('click',async e=>{const button=e.target.closest('button[data-approval]');if(!button)return;button.disabled=true;const response=await fetch('/api/pairing-requests/'+encodeURIComponent(button.dataset.approval),{method:'POST',headers:{'content-type':'application/json','x-browsermcp-csrf':csrf},body:JSON.stringify({decision:button.dataset.decision})});if(!response.ok){const result=await response.json().catch(()=>({error:'Approval request failed'}));alert(result.error)}await refresh()});
document.getElementById('pair').addEventListener('submit',async e=>{e.preventDefault();const output=document.getElementById('pair-output');const origin=new FormData(e.currentTarget).get('origin');const response=await fetch('/api/pairing-tokens',{method:'POST',headers:{'content-type':'application/json','x-browsermcp-csrf':csrf},body:JSON.stringify({origin})});const result=await response.json();output.textContent=response.ok?'Token (shown once): '+result.token+'\\nExpires: '+new Date(result.expiresAt).toLocaleString():result.error;});
refresh().catch(console.error);setInterval(()=>refresh().catch(console.error),2000);`
    : `document.getElementById('login').addEventListener('submit',async e=>{e.preventDefault();const output=document.getElementById('login-output');const token=new FormData(e.currentTarget).get('token');const response=await fetch('/api/ui-session',{method:'POST',headers:{authorization:'Bearer '+token}});if(response.ok){location.reload()}else{output.textContent='Authentication failed';e.currentTarget.reset()}});`;

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>BrowserMCP Bridge</title><style nonce="${nonce}">
:root{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:#daf7e9;background:#07110d}*{box-sizing:border-box}body{margin:0}header,main{width:min(1080px,calc(100% - 32px));margin:auto}header,.section-heading{display:flex;justify-content:space-between;align-items:center;gap:16px}header{padding:44px 0 22px}.eyebrow{margin:0;color:#6fe7ad;text-transform:uppercase;letter-spacing:.14em;font-size:12px}h1{font:600 clamp(28px,5vw,50px)/1.05 system-ui;margin:6px 0}h2{font:600 18px system-ui;margin:0 0 16px}.section-heading h2{margin:6px 0 16px}main{display:grid;gap:16px;padding-bottom:60px}section,article{border:1px solid #1d3d30;background:#0b1913;border-radius:12px;padding:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.stack{display:grid;gap:8px}.stack article{display:grid;grid-template-columns:minmax(120px,1fr) minmax(120px,2fr);gap:6px;padding:12px}.stack small,.stack code{grid-column:1/-1}.stack .approval{grid-template-columns:minmax(0,1fr) auto}.approval>div:first-child{display:grid;gap:6px}.actions{display:flex;align-items:center;gap:8px}.empty{color:#739485}.pill{border:1px solid #2d7455;border-radius:99px;padding:8px 12px;color:#6fe7ad}article{display:grid;gap:8px}article strong{font-size:30px;color:#6fe7ad}code{overflow-wrap:anywhere;color:#91bca7}small,.muted{color:#739485}.muted{line-height:1.55}form{display:flex;gap:10px;align-items:end;flex-wrap:wrap;margin-top:16px}label{display:grid;gap:7px;flex:1;min-width:260px}input{background:#06100c;border:1px solid #315945;border-radius:7px;color:inherit;padding:11px}button{background:#6fe7ad;border:0;border-radius:7px;color:#06100c;font-weight:700;padding:12px 16px;cursor:pointer}button:disabled{opacity:.5;cursor:wait}button.danger{background:#ff9c9c}summary{cursor:pointer;font:600 18px system-ui}output{display:block;white-space:pre-wrap;margin-top:12px;color:#ffe09a;overflow-wrap:anywhere}.login{min-height:100vh;place-items:center}.login section{max-width:620px}.error,.timeout,.cancelled{color:#ff9c9c}.success{color:#6fe7ad}@media(max-width:640px){.stack .approval{grid-template-columns:1fr}.actions{justify-content:flex-start}.section-heading{align-items:flex-start}}
</style></head><body>${body}<script nonce="${nonce}">${script}</script></body></html>`;
}
